export const ADD_VOTE = 'ADD_VOTE'
export const CREATE_ANECDOTE = 'CREATE_ANECDOTE'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'

export const SET_FILTER = 'SET_FILTER'
export const CLEAR_FILTER = 'CLEAR_FILTER'

